SET GLOBAL event_scheduler=ON;

DELIMITER $$

CREATE	EVENT RESET_SCHEDULE

ON SCHEDULE EVERY 1 DAY
	
DO
	BEGIN
	    UPDATE food_schedule SET REM_QTY=100 WHERE FOODTYPE_ID=1;
	    UPDATE food_schedule SET REM_QTY=75 WHERE FOODTYPE_ID=2;
	    UPDATE food_schedule SET REM_QTY=200 WHERE FOODTYPE_ID=3;
            UPDATE food_schedule SET REM_QTY=100 WHERE FOODTYPE_ID=4;
            TRUNCATE TABLE order_details;
	END$$

DELIMITER ;