DELIMITER $$
DROP PROCEDURE IF EXISTS PR_CANCEL_MULTI_ITEM $$

CREATE PROCEDURE PR_CANCEL_MULTI_ITEM(IN ORDER_ID INT,IN ITEM_LIST MEDIUMTEXT)
BEGIN
DECLARE ITEM_NAME TEXT DEFAULT NULL ;
DECLARE ITEM_LENGTH INT DEFAULT NULL;
DECLARE NEXT_ITEM TEXT DEFAULT NULL;        
        
iterator :    
LOOP            
IF LENGTH(TRIM(ITEM_LIST)) = 0 OR ITEM_LIST IS NULL  THEN
LEAVE iterator;
END IF;
               
SET ITEM_NAME = SUBSTRING_INDEX(ITEM_LIST,',',1);
SET ITEM_LENGTH = LENGTH(ITEM_NAME);             
SET NEXT_ITEM = TRIM(ITEM_NAME);

CALL PR_CANCEL_ORDER(ORDER_ID,ITEM_NAME);
                               
SET ITEM_LIST = INSERT(ITEM_LIST,1,ITEM_LENGTH + 1,'');              
END LOOP;

END$$

DELIMITER ;
